### ISSUE TITLE
Invalidation does not start after sls deploy

### ISSUE THREAD

**Issue by riccardolocci** [aghadiry/serverless-cloudfront-invalidate#16]
Running `sls deploy` does not run the invalidation at the end of the deployment of the project.
I have to separately run `sls cloudfrontInvalidate` after each deployment.

I have defined `serverless-cloudfront-invalidate` as the last plugin
```
plugins:
  - ...
  - serverless-cloudfront-invalidate
```

And I have configured it this way:
```
custom: 
  ...
  cloudfrontInvalidate:
    distributionIdKey: CDNDistributionId
    items:
      - "/*"
```

In the `Resources` block, my distribution is defined as follows:
```
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        ...
```

In the `Outputs` block, I have the following:
```  
  Outputs:
    CDNDistributionId:
      Description: CDN distribution id.
      Value:
        Ref: CloudFrontDistribution
```

With `sls cloudfrontInvalidate` all works

Some additional information:
* Serverless Version: `1.66.0`
* Node Version: `v13.6.0`
* NPM Version: `6.13.4`
* OS: `macOS 10.15.3 (Catalina)`
