### ISSUE TITLE
Can we have an option to conditionally disable or enable this plugin?

### ISSUE THREAD

**Issue by forabi** [aghadiry/serverless-cloudfront-invalidate#7]
I sometimes want to invalidate the cache only if the CI is deploying from the `master` branch. It would be convenient to be able to disable this plugin conditionally.

I can take a stab at this :smiley:

**Comment by coyoteecd** [comment]
@aghadiry are you maintaining this project? I also need an "enabled" property; assuming I submit a pull request, will you merge and publish it?

**Comment by mihaerzen** [comment]
I've added a PR that might help you with this. https://github.com/aghadiry/serverless-cloudfront-invalidate/pull/21

With this PR you could disable the `autoInvalidate` and in your CI pipeline invoke the `serverless cloudfrontInvalidate` where required.

**Comment by Ingordigia** [comment]
@mihaerzen I just added this plugin to my serverless project but the `autoInvalidate` flag doesn't seems to work to me.

My configuration is:

```yaml
cloudfrontInvalidate:
    - distributionIdKey: "CDNDistributionId" #conditional, distributionId or distributionIdKey is required.
      autoInvalidate: false # Can be set to false to avoid automatic invalidation after the deployment. Useful if you want to manually trigger the invalidation later. Defaults to true.
      items: # one or more paths required
        - "/*"
```
But the deploy pipeline is still invalidating twice.

Looking into the code i'm wondering if this line is correct https://github.com/aghadiry/serverless-cloudfront-invalidate/blob/581b8f8c57e569bc4adaf0a009a1f4e4f67bbf68/index.js#L44
because `autoInvalidate` is not an attribute of `cloudfrontInvalidate` but is an attribute of every element of the list.

Am I wrong ?
